support openfunction framework
OpenFunction/functions-framework-java pull request #1
Opened 2022-06-22 03:35 UTC by wanjunlei

2022-06-22 03:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenFunction/functions-framework-java?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenFunction/functions-framework-java?pullRequest=1) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenFunction/functions-framework-java?pullRequest=1) it.</sub>

2022-06-24 06:59 UTC, benjaminhuo requested changes

2022-06-24 06:59 UTC, benjaminhuo commented on functions-framework-invoker/src/main/java/dev/openfunction/invoker/context/UserContext.java
> +    private static final Map<String, Boolean> bindingQueueComponents = Map.of(
this hardcode bindingqueuecomponents is only used to determine if it's tracable?
@tpiperatgod Go FF has similar logic or use something else?

2022-06-24 06:59 UTC, benjaminhuo commented on functions-framework-invoker/src/main/java/dev/openfunction/invoker/context/UserContext.java
> +public class UserContext implements Context {
I think the `UserContext` can just be renamed to `Context` including class name and filename and variable name(lowercase)

2022-06-24 09:05 UTC, wanjunlei commented on samples/src/main/resources/function/http-with-output.yaml
> +metadata:
The samples and docs will be completed later.

2022-06-24 09:05 UTC, benjaminhuo commented on functions-framework-invoker/src/main/java/dev/openfunction/invoker/context/UserContext.java
> +public class UserContext implements Context {
Then we can use FuncContext instead?

2022-06-24 09:41 UTC, wanjunlei commented on functions-framework-invoker/src/main/java/dev/openfunction/invoker/context/UserContext.java
> +public class UserContext implements Context {
There has a class named FunctionContex.

2022-06-24 13:56 UTC, benjaminhuo commented on functions-framework-invoker/src/main/java/dev/openfunction/invoker/context/UserContext.java
> +public class UserContext implements Context {
what's the difference between FunctionContex and UserContext?

2022-06-27 00:37 UTC, wanjunlei commented on functions-framework-invoker/src/main/java/dev/openfunction/invoker/context/UserContext.java
> +public class UserContext implements Context {
The `FunctionContex` is the structure of `FUNC_CONTEXT`, `UserContext` implement the `Context` interface and will pass to the function.

2022-06-27 02:00 UTC, benjaminhuo commented on functions-framework-invoker/src/main/java/dev/openfunction/invoker/context/UserContext.java
> +public class UserContext implements Context {
That's ok if user function can only see context interface

2022-06-27 02:00 UTC, merged